version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DEV_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DEV_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${DEV_POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tinyshop:
    build:
      context: .
      dockerfile: Dockerfile
      target: build        # SDK-Image für dotnet watch
    env_file:
      - .env
    volumes:
      - ./TinyShop.Web:/src/TinyShop.Web:delegated
      - ./TinyShop.Application:/src/TinyShop.Application:delegated
      - ./TinyShop.Infrastructure:/src/TinyShop.Infrastructure:delegated
      - ./TinyShop.Domain:/src/TinyShop.Domain:delegated
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:${PORT}"
      ConnectionStrings__DefaultConnection: >-
        Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};
        Database=${DEV_POSTGRES_DB};Username=${DEV_POSTGRES_USER};
        Password=${DEV_POSTGRES_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres

volumes:
  pgdata:
