version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tinyshop-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DEV_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DEV_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${DEV_POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
