version: '3.8'

services:
  tinyshop:
    build:
      context: .
      dockerfile: Dockerfile
      target: build           # verwendet das SDK-Image für dotnet watch
    env_file:
      - .env
    volumes:
      - ./TinyShop.Web:/src/TinyShop.Web:delegated
      - ./TinyShop.Application:/src/TinyShop.Application:delegated
      - ./TinyShop.Infrastructure:/src/TinyShop.Infrastructure:delegated
      - ./TinyShop.Domain:/src/TinyShop.Domain:delegated
    working_dir: /src/TinyShop.Web
    # wir legen hier den Listen-Port auf 85 fest
    command: dotnet watch run --urls=http://0.0.0.0:85
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >-
        Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};
        Database=${DEV_POSTGRES_DB};Username=${DEV_POSTGRES_USER};
        Password=${DEV_POSTGRES_PASSWORD}
    ports:
      - "85:85"               # hostPort:containerPort
    depends_on:
      - postgres
    restart: on-failure
