version: '3.8'

services:
  tinyapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./TinyShop.API:/src/TinyShop.API:delegated
      - ./TinyShop.Application:/src/TinyShop.Application:delegated
      - ./TinyShop.Infrastructure:/src/TinyShop.Infrastructure:delegated
      - ./TinyShop.Domain:/src/TinyShop.Domain:delegated
    working_dir: /src/TinyShop.API
    command: dotnet watch run --urls=http://0.0.0.0:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=postgres;Database=tinyshopdb;Username=postgres;Password=postgres"
    ports:
      - "5000:80"
    depends_on:
      - postgres
    restart: on-failure
