version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tinyshop-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${PROD_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${PROD_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${PROD_POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

  tinyshop:
    build:
      context: .
      dockerfile: Dockerfile
      # kein target: so nimmt Docker den letzten (Runtime‑) Stage
    container_name: tinyshop
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:85"
      ConnectionStrings__DefaultConnection: >-
        Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};
        Database=${PROD_POSTGRES_DB};Username=${PROD_POSTGRES_USER};
        Password=${PROD_POSTGRES_PASSWORD}
    depends_on:
      - postgres
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.tinyshop.rule=Host(`tinyshop.simonfischer.dev`)"
      - "traefik.http.routers.tinyshop.entrypoints=websecure"
      - "traefik.http.routers.tinyshop.tls.certresolver=basic"
      - "traefik.http.services.tinyshop.loadbalancer.server.port=85"
    networks:
      - default
      - traefik

volumes:
  pgdata:

networks:
  default:
    driver: bridge
  traefik:
    external: true
